version: '2'
services:
  server:
    image: abiosoft/caddy:0.10.3
    environment:
      - CADDYPATH=/etc/caddycerts
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./dev:/etc/caddycerts
      - ./dist:/var/docker.dev
  asset:
    build:
      context: .
      dockerfile: Dockerfile.asset
    volumes:
      - ./dist:/var/assets_build/output
      - ./tsconfig.json:/var/assets_build/tsconfig.json
      - ./webpack.config.js:/var/assets_build/webpack.config.js
      - ./yarn.lock:/var/assets_build/yarn.lock
      - ./package.json:/var/assets_build/package.json
      - ./src:/var/assets_build/input
